<?php
/**
 * Created by PhpStorm.
 * Author: Floating dust
 * Date: 2017-11-11
 * Time: 22:02
 */

namespace backend\filters;


use yii\base\ActionFilter;
use yii\web\HttpException;



class IsUserFilters extends ActionFilter
{
    public function beforeAction($action)
    {
        if (\Yii::$app->user->isGuest)
        {
            //重定向浏览器
            header("Location: /admin/login");
//确保重定向后，后续代码不会被执行
            exit;



//          throw new HttpException(404,"你没有权限执行此操作");
     //       throw new HttpException(403,'你没有权限执行此操作');
        }

//        if (!\Yii::$app->user->can($action->uniqueId)){
//          //  throw new HttpException(403,'你没有权限执行此操作');
//            return '0';
//        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

}